[package]
name = "derive-macro-bug"
version = "0.0.0"
authors = ["philipahlberg <philipahlberg@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"

[dev-dependencies]
trybuild = "1.0"
